<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Core_extended__Exception_check (core_extended.Core_extended__Exception_check)</title><link rel="stylesheet" href="../../_odoc-theme/odoc.css"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><div class="content"><header><nav><a href="../index.html">Up</a> â€“ <a href="../index.html">core_extended</a> &#x00BB; Core_extended__Exception_check</nav><h1>Module <code>Core_extended__Exception_check</code></h1><p>Code to test the effect of exceptions happening in strategic places in daemons.</p><p>In order to use this module one defines a list of (mnemonic, exception) pairs</p><p>E.G.</p><p><code>(&quot;M.f: invalid arg&quot;, Invalid_argument &quot;foo&quot;);
     (&quot;Z.f: sys error&quot;, Sys_error &quot;bar&quot;);
     (&quot;R.z: failure&quot;, Failure &quot;baz&quot;)</code></p><p>And one passes this list to create. Then one places calls to Exception_check.maybe_raise &lt;name&gt;, in important parts of one's code. When the code is run, it will listen on <code>listen_port</code>, and one can connect with netcat and type a name, which will cause that exception to be raised on the next call to <code>Exception_check.maybe_raise</code>.</p></header><dl><dt class="spec value" id="val-create"><a href="#val-create" class="anchor"></a><code><span class="keyword">val</span> create : ?&#8288;listen_port:int <span>&#45;&gt;</span> (string * exn) list <span>&#45;&gt;</span> unit</code></dt><dd><p>create should not be called more than once</p></dd></dl><dl><dt class="spec value" id="val-maybe_raise"><a href="#val-maybe_raise" class="anchor"></a><code><span class="keyword">val</span> maybe_raise : string list <span>&#45;&gt;</span> unit</code></dt><dd><p><code>maybe_raise name</code> if the exception associated with any name in <code>name</code> has been triggered, then raise it, otherwise do nothing. Only the first exception in the list will be raised. This function is thread safe.</p></dd></dl></div></body></html>